import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "../provider/ReduxProvider";
import { ThirdWebprovider } from "@/provider/ThirdWebprovider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}   >
  
        < ThirdWebprovider>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </ThirdWebprovider>
      </body>
    </html>
  );
}
