import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ReduxProvider } from "../provider/ReduxProvider";
import { ThirdWebprovider } from "@/provider/ThirdWebprovider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import Navbar from "@/components/Navbar/Navbar";
import { SideBar } from "@/components/Sidebar/SideBar";
import Footer from "@/components/Footer/Footer";



export const metadata = {
  title: "CrowdX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <html lang="en">
      <body className={` antialiased w-full min-h-screen ` }>
        <ThirdWebprovider>
          <ReduxProvider>
            <SidebarProvider >
              <div className="flex min-h-screen w-full bg-black text-white">
                {/* Sidebar with trigger inside */}
                <div className="flex flex-col items-center bg-[#0a0a0a]">
                  <SideBar />
                </div>
                  <SidebarTrigger />

                {/* Main content */}
                <div className="flex-1 flex flex-col pr-7 py-4">
                  <Navbar />
                  <main className="mt-4">{children}</main>
                </div>
              </div>
            </SidebarProvider>
          </ReduxProvider>
        </ThirdWebprovider>
        <Footer />
      </body>
    </html>    

  );
}


