import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "../provider/ReduxProvider";
import { ThirdWebprovider } from "@/provider/ThirdWebprovider";
import Navbar from "@/components/Navbar/Navbar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CrowdX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased w-[92%] mx-auto`}   >
        < ThirdWebprovider>
         <Navbar />

          <ReduxProvider>
            {children}
          </ReduxProvider>
        </ThirdWebprovider>
      </body>
    </html>
  );
}
